[tool.portray]
name = "helpers"
version = "0.2"
description = "A library of python helpers"
authors = "stablecaps 114529342+darkpandarts@users.noreply.github.com"
homepage = "https://github.com/stablecaps/helpohelpo.git"
modules = ["helpers"]
license = "MIT"
packages = [
    { include = "helpers/*.py" }
]

# https://timothycrosley.github.io/portray/reference/portray/render/
docs_dir = "markdown"
output_dir = "docs"
include_reference_documentation = true

[tool.portray.mkdocs]
extra_css = ["css/extra.css"]

[tool.portray.mkdocs.theme]
name = "windmill-dark"
favicon = "img/favicon.ico"




[[tool.portray.mkdocs.nav]]
Home = "README.md"

