# publish
# https://docs.pypi.org/trusted-publishers/

on:
    push:
      branches:
        - feature/setup-semvar-pipeline
        - master
    pull_request:
      branches: [ main ]

# TODO: insert linting checks & tests
jobs:
  build-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"

    - name: Install dependencies
      run: |
        poetry install

    # - name: Run tests
    #   run: |
    #     poetry run pytest


    # - uses: actions/upload-artifact@v3
    #   with:
    #     path: ./dist

  publish:
    needs: ['build-test']
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(release):')
    name: upload release to PyPI
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8"]
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies & build package
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Prepare package for release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry run semantic-release version
          poetry run semantic-release publish

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   packages-dir: artifact/
##

# https://endjin.com/blog/2023/02/how-to-implement-continuous-deployment-of-python-packages-with-github-actions
# https://ubc-mds.github.io/DSCI_524_collab-sw-dev/materials/lectures/06_lecture-cd-semver-and-docs.html
# https://dev.to/mestrak/semantic-release-with-python-poetry-github-actions-20nn
# https://github.com/Ezard/semantic-prs
# https://michaelheap.com/ultimate-guide-github-actions-authentication/