# publish
# https://docs.pypi.org/trusted-publishers/

on:
    push:
      branches:
        - master
        - release/*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Build package
      run: poetry build

    - uses: actions/upload-artifact@v3
      with:
        path: ./dist

  pypi-publish:
    needs: ['build']
    # environment: 'publish'

    name: upload release to PyPI
    runs-on: ubuntu-22.04
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v3

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/
##

